## Numpy簡介

Numpy 本是Python的線性代數套件，對於機器學習的應用相當重要

本課程中不討論機器學習的範疇，而將著重在利用Numpy提供的強大功能對資料進行處理的過程

## Numpy Array (ndarray)

即向量與矩陣

一維Array稱為向量(vector)

二維Array稱為矩陣(matrix)

- ### 建構

In [32]:
import numpy as np

In [2]:
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [3]:
mat = np.array([[1,2,3], [4,5,6]])
mat

array([[1, 2, 3],
       [4, 5, 6]])

---

## 基本特性

- ### ndarray中每一個元素的型態理論上都是相同的，但...

In [4]:
arr = np.array([1,2,'3'])
arr

array(['1', '2', '3'], dtype='<U11')

In [33]:
arr = np.array([1,2,None])
arr

array([1, 2, None], dtype=object)

- ### shape: 查看ndarray維度

In [8]:
mat = np.array([[1,2,3], [4,5,6]])
mat

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
mat.shape

(2, 3)

- ### size: 查看ndarray元素數量

In [9]:
mat = np.array([[1,2,3], [4,5,6]])
mat

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
mat.size

6

- ### dtype: 查看資料型態

In [18]:
arr = np.array([1,2,3])
arr.dtype

dtype('int32')

---

## 其他建構方法

- ### np.ones()

In [11]:
all_ones = np.ones((3,4))
all_ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

- ### np.zeros()

In [12]:
all_zeros = np.zeros((3,4))
all_zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

- ### np.arange()

In [17]:
arr = np.arange(16)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

---

## Random in Numpy

- ### np.random

In [13]:
np.random.random((3,3))

array([[0.87082429, 0.08241965, 0.19264253],
       [0.00173441, 0.9962217 , 0.67610209],
       [0.34191116, 0.23957333, 0.96726241]])

In [16]:
np.random.randint(0, 10, (5,))

array([6, 3, 3, 4, 7])

- ### random seed
確保每次random結果都相同

In [20]:
np.random.seed(24)
np.random.random((3,3))

array([[0.9600173 , 0.69951205, 0.99986729],
       [0.2200673 , 0.36105635, 0.73984099],
       [0.99645573, 0.31634698, 0.13654458]])

---

## 基本操作

- ### 選取row/column資料

In [21]:
mat = np.array([[1,2,3], [4,5,6], [7,8,9]])
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

    - 使用索引

In [22]:
mat[0]

array([1, 2, 3])

In [23]:
mat[0][0]

1

- 使用分片

In [26]:
mat[:2, :2]

array([[1, 2],
       [4, 5]])

In [25]:
mat[:2, 1:]

array([[2, 3],
       [5, 6]])

- ### reshape

In [29]:
arr = np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

In [30]:
arr.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [31]:
arr.reshape(-1,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])